<?php

$title = 'Add new task';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$task = $form->get('title');
$task->setAttribute('class', 'form-control');
$task->setAttribute('placeholder', 'Task title');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

// Set status to 1 initally
$status = $form->get('status');
$status->setValue(1);

$form->setAttribute('action', $this->url('task', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within ?>
    <div class="form-group">
        <?= $this->formLabel($task) ?>
        <?= $this->formElement($task) ?>
        <?= $this->formElementErrors()->render($task, ['class' => 'help-block']) ?>
    </div>
<?php

echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('userid'));
echo $this->formHidden($status);
echo $this->form()->closeTag();