<?php

$title = 'Edit task';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
$task = $form->get('title');
$task->setAttribute('class', 'form-control');
$task->setAttribute('placeholder', 'Task title');

$status = $form->get('status');
$status->setAttribute('class', 'form-control');
$status->setAttribute('placeholder', 'Status');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('task', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
    <div class="form-group">
        <?= $this->formLabel($task) ?>
        <?= $this->formElement($task) ?>
        <?= $this->formElementErrors()->render($task, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($status) ?>
        <?= $this->formElement($status) ?>
        <?= $this->formElementErrors()->render($task, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('userid'));
echo $this->form()->closeTag();